// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shpsfophjepnogjojlsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocHNmb3BoamVwbm9nam9qbHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTQ0MTUsImV4cCI6MjA3MTkzMDQxNX0.aBMgmieFhRYhwUAgFoad1SoL7ouBCiDGYoX2Z_rotM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});